//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recepies.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepy
    {
        public Recepy()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int RecepieId { get; set; }
        public string Name { get; set; }
        public string Products { get; set; }
        public string CookingSteps { get; set; }
        public string ImagePath { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
    }
}
