//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recepies.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbcc87f75bab1e4f11b506a23a00be151aEntities : DbContext
    {
        public dbcc87f75bab1e4f11b506a23a00be151aEntities()
            : base("name=dbcc87f75bab1e4f11b506a23a00be151aEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Recepy> Recepies { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
